version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "weare"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "weare"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "weare"
    labels:
      - "dependencies"
      - "contracts"
    commit-message:
      prefix: "chore(contracts)"
      include: "scope"
