[package]
name = "content-management-system"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "27.0.6"

[dev-dependencies]
soroban-sdk = { version = "27.0.6", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
