/**
 * Open Source License Data
 *
 * Comprehensive dataset of the most commonly used open source licenses,
 * including their permissions, conditions, limitations, and use case suitability.
 */
import type { License } from './types.js';

export const licenses: License[] = [
  // ===== PERMISSIVE LICENSES =====
  {
    id: 'mit',
    name: 'MIT License',
    fullName: 'MIT License',
    spdxId: 'MIT',
    category: 'permissive',
    description:
      'The MIT License is a permissive free software license originating at the Massachusetts Institute of Technology. It permits reuse within proprietary software provided the license copy is included.',
    summary:
      'A short, permissive license that allows almost any use, as long as the copyright notice is preserved.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'very-high',
    recommendedFor: [
      'Small to medium projects',
      'Libraries and frameworks',
      'Commercial products',
      'Web applications',
      'Desktop applications',
    ],
    notRecommendedFor: [
      'Projects requiring strong copyleft protection',
      'Projects where you want to prevent proprietary use',
    ],
    url: 'https://opensource.org/licenses/MIT',
    tags: ['popular', 'simple', 'permissive', 'business-friendly'],
  },
  {
    id: 'apache-2.0',
    name: 'Apache License 2.0',
    fullName: 'Apache License, Version 2.0',
    spdxId: 'Apache-2.0',
    category: 'permissive',
    description:
      'A permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights.',
    summary:
      'Like MIT but with an explicit patent grant from contributors. Good for projects that may involve patents.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: true,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: true,
      patentRetaliation: true,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'very-high',
    recommendedFor: [
      'Projects with patent concerns',
      'Large corporate projects',
      'Libraries and frameworks',
      'Projects requiring a patent grant',
    ],
    notRecommendedFor: [
      'Developers wanting a simpler, shorter license',
      'Projects that want to avoid trademark clauses',
    ],
    url: 'https://www.apache.org/licenses/LICENSE-2.0',
    tags: ['popular', 'permissive', 'patent', 'corporate-friendly'],
  },
  {
    id: 'bsd-2-clause',
    name: 'BSD 2-Clause License',
    fullName: 'BSD 2-Clause "Simplified" License',
    spdxId: 'BSD-2-Clause',
    category: 'permissive',
    description:
      'A permissive license that comes in two variants. The BSD 2-clause license allows redistribution and use as long as the copyright and license notices are retained.',
    summary:
      'A simple permissive license similar to MIT but with slightly different wording around endorsement.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'Projects wanting MIT-like terms',
      'Projects wanting to restrict endorsement',
      'University projects',
    ],
    notRecommendedFor: [
      'Projects with patent concerns',
    ],
    url: 'https://opensource.org/licenses/BSD-2-Clause',
    tags: ['permissive', 'simple', 'academic'],
  },
  {
    id: 'bsd-3-clause',
    name: 'BSD 3-Clause License',
    fullName: 'BSD 3-Clause "New" or "Revised" License',
    spdxId: 'BSD-3-Clause',
    category: 'permissive',
    description:
      'The BSD 3-clause license allows redistribution and use in source and binary forms, with or without modification, provided the conditions are met. It adds a clause prohibiting the use of the project contributors\' names for promotion.',
    summary:
      'Like BSD 2-Clause but with an additional clause prohibiting endorsement misuse.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: true,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'Projects where endorsement protection matters',
      'University and research projects',
      'Government projects',
    ],
    notRecommendedFor: [
      'Projects wanting simpler terms (use MIT)',
    ],
    url: 'https://opensource.org/licenses/BSD-3-Clause',
    tags: ['permissive', 'academic', 'endorsement-protection'],
  },
  {
    id: 'isc',
    name: 'ISC License',
    fullName: 'ISC License',
    spdxId: 'ISC',
    category: 'permissive',
    description:
      'The ISC license is functionally equivalent to the MIT License but uses simpler, shorter language. It removes some wording that some consider unnecessary.',
    summary:
      'A permissive license functionally identical to MIT but with simpler, shorter text.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'npm packages and Node.js projects',
      'Small projects wanting minimal license text',
    ],
    notRecommendedFor: [
      'Projects needing explicit patent grants',
    ],
    url: 'https://opensource.org/licenses/ISC',
    tags: ['permissive', 'minimal', 'npm'],
  },
  {
    id: 'unlicense',
    name: 'The Unlicense',
    fullName: 'The Unlicense',
    spdxId: 'Unlicense',
    category: 'public-domain',
    description:
      'A license with no conditions whatsoever which dedicates works to the public domain. Unlicensed works, modifications, and larger works may be distributed under different terms and without source code.',
    summary:
      'Dedicates the work to the public domain. No restrictions on use whatsoever.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: true,
      trademarkUse: true,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: false,
      includeLicense: false,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: false,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'medium',
    recommendedFor: [
      'Projects where you want maximum adoption',
      'Trivial code snippets',
      'Anti-copyright projects',
    ],
    notRecommendedFor: [
      'Projects in jurisdictions without public domain',
      'Projects needing attribution protection',
    ],
    url: 'https://unlicense.org/',
    tags: ['public-domain', 'maximally-permissive', 'no-attribution'],
  },
  {
    id: 'cc0-1.0',
    name: 'CC0 1.0 Universal',
    fullName: 'Creative Commons CC0 1.0 Universal',
    spdxId: 'CC0-1.0',
    category: 'public-domain',
    description:
      'CC0 enables creators to waive all copyright and related rights in their works to the fullest extent allowed by law, effectively placing them in the public domain.',
    summary:
      'A public domain dedication that waives all copyright rights worldwide.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: false,
      includeLicense: false,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: false,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'Data and databases',
      'Creative works and content',
      'Scientific datasets',
      'Projects wanting maximum reuse',
    ],
    notRecommendedFor: [
      'Software (use a software-specific license)',
      'Projects needing attribution',
    ],
    url: 'https://creativecommons.org/publicdomain/zero/1.0/',
    tags: ['public-domain', 'data', 'creative-works'],
  },

  // ===== WEAK COPYLEFT LICENSES =====
  {
    id: 'lgpl-3.0',
    name: 'GNU LGPLv3',
    fullName: 'GNU Lesser General Public License v3.0',
    spdxId: 'LGPL-3.0-only',
    category: 'weak-copyleft',
    description:
      'The LGPL is a weaker copyleft license that allows linking into proprietary projects as a library, as long as the library itself remains LGPL-licensed and users can modify it.',
    summary:
      'Lets you use the library in proprietary projects but modifications to the library itself must stay LGPL.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: true,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: true,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: true,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'possible',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'not-recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'Software libraries',
      'Frameworks',
      'Plugins for proprietary software',
    ],
    notRecommendedFor: [
      'Standalone applications',
      'Projects that want strong copyleft',
    ],
    url: 'https://www.gnu.org/licenses/lgpl-3.0.html',
    tags: ['copyleft', 'library-friendly', 'lgpl'],
  },
  {
    id: 'lgpl-2.1',
    name: 'GNU LGPLv2.1',
    fullName: 'GNU Lesser General Public License v2.1',
    spdxId: 'LGPL-2.1-only',
    category: 'weak-copyleft',
    description:
      'The LGPL version 2.1 is a weaker copyleft license that allows proprietary applications to link to the library. Modifications to the library itself must be released under LGPL.',
    summary:
      'Similar to LGPLv3 but without the explicit patent grant. Often used for older libraries.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: true,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'possible',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'not-recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'Older projects already using LGPLv2.1',
      'Libraries where LGPLv3 is too restrictive',
    ],
    notRecommendedFor: [
      'New projects (prefer LGPLv3 for patent protection)',
    ],
    url: 'https://www.gnu.org/licenses/lgpl-2.1.html',
    tags: ['copyleft', 'library-friendly', 'lgpl', 'legacy'],
  },
  {
    id: 'mpl-2.0',
    name: 'Mozilla Public License 2.0',
    fullName: 'Mozilla Public License 2.0',
    spdxId: 'MPL-2.0',
    category: 'weak-copyleft',
    description:
      'The MPL is a hybrid license that requires modifications to files that are MPL-licensed to be released under MPL, but allows larger works to combine MPL-licensed files with proprietary files.',
    summary:
      'File-level copyleft. Changes to MPL files must be shared, but new files can be proprietary.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: true,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: true,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'possible',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'not-recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'Projects wanting to allow proprietary integration',
      'File-level copyleft protection',
      'Projects with patent concerns',
    ],
    notRecommendedFor: [
      'Projects wanting full copyleft protection',
      'Simple scripts or small projects',
    ],
    url: 'https://www.mozilla.org/en-US/MPL/2.0/',
    tags: ['copyleft', 'file-level', 'hybrid', 'mozilla'],
  },

  // ===== COPYLEFT LICENSES =====
  {
    id: 'gpl-3.0',
    name: 'GNU GPLv3',
    fullName: 'GNU General Public License v3.0',
    spdxId: 'GPL-3.0-only',
    category: 'copyleft',
    description:
      'The GPL is a strong copyleft license that requires anyone who distributes modified versions or derivative works to release the complete source code under the same license.',
    summary:
      'Strong copyleft: if you distribute the software, you must share your source under GPLv3.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: true,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: true,
      includeNotice: true,
      includeInstallInstructions: true,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: true,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'possible',
      saas: 'recommended',
      library: 'not-recommended',
      documentation: 'restricted',
      educational: 'recommended',
    },
    popularity: 'very-high',
    recommendedFor: [
      'Projects ensuring all derivatives remain free',
      'Desktop applications',
      'Embedded software',
    ],
    notRecommendedFor: [
      'Libraries (use LGPL instead)',
      'Projects designed for SaaS use (no distribution trigger)',
      'Commercial products wanting to keep source proprietary',
    ],
    url: 'https://www.gnu.org/licenses/gpl-3.0.html',
    tags: ['copyleft', 'strong-copyleft', 'fsf', 'gpl'],
  },
  {
    id: 'gpl-2.0',
    name: 'GNU GPLv2',
    fullName: 'GNU General Public License v2.0',
    spdxId: 'GPL-2.0-only',
    category: 'copyleft',
    description:
      'The GPL version 2 is a strong copyleft license that requires source code distribution for any distributed modifications. It lacks the patent and anti-TiVoization clauses of GPLv3.',
    summary:
      'Strong copyleft like GPLv3 but without patent grant or anti-Tivoization provisions.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: true,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'possible',
      saas: 'recommended',
      library: 'not-recommended',
      documentation: 'restricted',
      educational: 'recommended',
    },
    popularity: 'very-high',
    recommendedFor: [
      'Legacy projects already using GPLv2',
      'Linux kernel modules',
      'Projects preferring older licensing terms',
    ],
    notRecommendedFor: [
      'New projects (prefer GPLv3 for patent protection)',
      'Libraries or frameworks',
    ],
    url: 'https://www.gnu.org/licenses/gpl-2.0.html',
    tags: ['copyleft', 'strong-copyleft', 'fsf', 'gpl', 'legacy'],
  },
  {
    id: 'agpl-3.0',
    name: 'GNU AGPLv3',
    fullName: 'GNU Affero General Public License v3.0',
    spdxId: 'AGPL-3.0-only',
    category: 'network-copyleft',
    description:
      'The AGPL is the strongest copyleft license. It extends GPLv3 to close the "SaaS loophole" — if you modify the software and run it on a network (as a web service), users who interact with it over the network have the right to access the source code.',
    summary:
      'Strongest copyleft: if you run modified code as a web service, users can request the source.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: true,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: true,
      includeNotice: true,
      includeInstallInstructions: true,
      networkUseDisclosure: true,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: true,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'restricted',
      saas: 'recommended',
      library: 'restricted',
      documentation: 'restricted',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'SaaS and web applications',
      'Network services',
      'Projects wanting maximum copyleft protection',
      'Server-side software',
    ],
    notRecommendedFor: [
      'Client-side libraries',
      'Desktop applications with no network interaction',
      'Commercial SaaS products wanting closed source',
    ],
    url: 'https://www.gnu.org/licenses/agpl-3.0.html',
    tags: ['copyleft', 'strongest-copyleft', 'saas', 'network'],
  },

  // ===== OTHER LICENSES =====
  {
    id: 'epl-2.0',
    name: 'Eclipse Public License 2.0',
    fullName: 'Eclipse Public License 2.0',
    spdxId: 'EPL-2.0',
    category: 'weak-copyleft',
    description:
      'The EPL is a weak copyleft license used primarily for Eclipse Foundation projects. It allows combining EPL-licensed code with proprietary code in larger works.',
    summary:
      'Weak copyleft used by Eclipse Foundation. Patent retaliation clause included.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: true,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: true,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: true,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'possible',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'not-recommended',
      educational: 'recommended',
    },
    popularity: 'medium',
    recommendedFor: [
      'Eclipse Foundation projects',
      'Commercial-friendly copyleft projects',
      'Java/IDE plugins',
    ],
    notRecommendedFor: [
      'Non-Eclipse ecosystem projects',
      'Projects outside the Java ecosystem',
    ],
    url: 'https://www.eclipse.org/legal/epl-2.0/',
    tags: ['copyleft', 'eclipse', 'java'],
  },
  {
    id: 'bsl-1.1',
    name: 'Business Source License 1.1',
    fullName: 'Business Source License 1.1',
    spdxId: 'BUSL-1.1',
    category: 'other',
    description:
      'The BUSL is a source-available license that grants rights to use, modify, and share the software for non-production uses. Production use requires a commercial license. It converts to a standard open source license (usually GPL or Apache) after a change date.',
    summary:
      'Source-available license with a time-limited restriction on production use. Converts to open source later.',
    permissions: {
      commercialUse: false,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: true,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: true,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'restricted',
      saas: 'restricted',
      library: 'restricted',
      documentation: 'not-recommended',
      educational: 'recommended',
    },
    popularity: 'medium',
    recommendedFor: [
      'Commercial open source business models',
      'Projects with a dual-license strategy',
      'Companies wanting to monetize while being transparent',
    ],
    notRecommendedFor: [
      'Standard open source projects',
      'Projects wanting OSI approval (BUSL is not OSI-approved)',
    ],
    url: 'https://mariadb.com/bsl11/',
    tags: ['source-available', 'commercial', 'time-limited'],
  },
  {
    id: 'cc-by-4.0',
    name: 'Creative Commons Attribution 4.0',
    fullName: 'Creative Commons Attribution 4.0 International',
    spdxId: 'CC-BY-4.0',
    category: 'permissive',
    description:
      'CC BY allows others to distribute, remix, adapt, and build upon the material in any medium or format, so long as attribution is given to the creator. It is the least restrictive of the CC licenses.',
    summary:
      'Allows any use as long as attribution is provided. Best for documentation and creative works.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: false,
      stateChanges: true,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'not-recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'very-high',
    recommendedFor: [
      'Documentation',
      'Educational materials',
      'Creative works',
      'Blog posts and articles',
    ],
    notRecommendedFor: [
      'Software code (use a software license)',
      'Projects wanting no-attribution use',
    ],
    url: 'https://creativecommons.org/licenses/by/4.0/',
    tags: ['creative-commons', 'attribution', 'documentation'],
  },
  {
    id: 'cc-by-sa-4.0',
    name: 'Creative Commons Attribution-ShareAlike 4.0',
    fullName: 'Creative Commons Attribution-ShareAlike 4.0 International',
    spdxId: 'CC-BY-SA-4.0',
    category: 'copyleft',
    description:
      'CC BY-SA lets others remix, adapt, and build upon the material for any purpose, even commercially, as long as they credit the creator and license their new creations under identical terms.',
    summary:
      'Attribution required and derivative works must use the same license. The "copyleft" CC license.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: false,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: true,
      discloseSource: false,
      sameLicense: true,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'possible',
      saas: 'possible',
      library: 'not-recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'high',
    recommendedFor: [
      'Documentation requiring share-alike',
      'Wikipedia content',
      'Educational course materials',
    ],
    notRecommendedFor: [
      'Software code',
      'Projects with patent concerns',
    ],
    url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    tags: ['creative-commons', 'copyleft', 'share-alike'],
  },
  {
    id: 'zlib',
    name: 'Zlib License',
    fullName: 'Zlib License',
    spdxId: 'Zlib',
    category: 'permissive',
    description:
      'The zlib license is a very short, permissive license used for the zlib compression library. It allows the software to be used, modified, and distributed freely.',
    summary:
      'A very short, simple permissive license. Used primarily for compression libraries.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'medium',
    recommendedFor: [
      'Embedded software and drivers',
      'Game development',
      'Projects wanting minimal license text',
    ],
    notRecommendedFor: [
      'Projects needing patent protection',
    ],
    url: 'https://opensource.org/licenses/Zlib',
    tags: ['permissive', 'minimal', 'embedded'],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL License',
    fullName: 'PostgreSQL License',
    spdxId: 'PostgreSQL',
    category: 'permissive',
    description:
      'The PostgreSQL license is a permissive license similar to the MIT License. It allows the software to be used, modified, and distributed with no restrictions beyond preserving the copyright and disclaimer.',
    summary:
      'A permissive license similar to MIT used by the PostgreSQL database.',
    permissions: {
      commercialUse: true,
      modification: true,
      distribution: true,
      privateUse: true,
      patentUse: false,
      trademarkUse: false,
      sublicense: true,
      warranty: false,
    },
    conditions: {
      includeCopyright: true,
      includeLicense: true,
      stateChanges: false,
      discloseSource: false,
      sameLicense: false,
      includeNotice: true,
      includeInstallInstructions: false,
      networkUseDisclosure: false,
    },
    limitations: {
      liability: true,
      warranty: true,
      trademark: false,
      patentRetaliation: false,
      useRestriction: false,
    },
    useCaseSuitability: {
      personal: 'recommended',
      commercial: 'recommended',
      saas: 'recommended',
      library: 'recommended',
      documentation: 'recommended',
      educational: 'recommended',
    },
    popularity: 'medium',
    recommendedFor: [
      'Database-related projects',
      'Projects following the PostgreSQL model',
    ],
    notRecommendedFor: [
      'Projects needing explicit patent grants',
    ],
    url: 'https://opensource.org/licenses/PostgreSQL',
    tags: ['permissive', 'database'],
  },
];

/**
 * Compatibility matrix defining how licenses relate to each other.
 * Only non-trivial compatibilities are listed. Licenses not listed
 * should be treated as "conditional" (requires legal review).
 */
export const compatibilityMatrix: Array<{
  licenseA: string;
  licenseB: string;
  compatibility: 'compatible' | 'conditional' | 'incompatible';
  conditions?: string;
}> = [
  // MIT compatibility
  { licenseA: 'mit', licenseB: 'apache-2.0', compatibility: 'compatible', conditions: 'When combining, the Apache NOTICE file must be preserved.' },
  { licenseA: 'mit', licenseB: 'bsd-2-clause', compatibility: 'compatible' },
  { licenseA: 'mit', licenseB: 'bsd-3-clause', compatibility: 'compatible' },
  { licenseA: 'mit', licenseB: 'isc', compatibility: 'compatible' },
  { licenseA: 'mit', licenseB: 'unlicense', compatibility: 'compatible' },
  { licenseA: 'mit', licenseB: 'cc0-1.0', compatibility: 'compatible' },
  { licenseA: 'mit', licenseB: 'zlib', compatibility: 'compatible' },
  { licenseA: 'mit', licenseB: 'postgresql', compatibility: 'compatible' },
  { licenseA: 'mit', licenseB: 'gpl-2.0', compatibility: 'compatible', conditions: 'MIT code can be included in GPLv2 projects (GPLv2 accepts MIT-licensed code). However, the combined work must be distributed under GPLv2.' },
  { licenseA: 'mit', licenseB: 'gpl-3.0', compatibility: 'compatible', conditions: 'MIT code can be included in GPLv3 projects. Combined work must be under GPLv3. GPLv3 is compatible with MIT.' },
  { licenseA: 'mit', licenseB: 'agpl-3.0', compatibility: 'compatible', conditions: 'MIT code can be included in AGPLv3 projects. Combined work must be under AGPLv3.' },
  { licenseA: 'mit', licenseB: 'lgpl-3.0', compatibility: 'compatible', conditions: 'MIT code can be used in LGPLv3 projects. The LGPL library must remain under LGPL, but the MIT code can be used freely.' },
  { licenseA: 'mit', licenseB: 'mpl-2.0', compatibility: 'compatible', conditions: 'MIT-licensed files can be included in MPL-2.0 projects. MPL applies only to modified MPL files.' },

  // Apache 2.0 compatibility
  { licenseA: 'apache-2.0', licenseB: 'bsd-2-clause', compatibility: 'compatible' },
  { licenseA: 'apache-2.0', licenseB: 'bsd-3-clause', compatibility: 'compatible' },
  { licenseA: 'apache-2.0', licenseB: 'isc', compatibility: 'compatible' },
  { licenseA: 'apache-2.0', licenseB: 'unlicense', compatibility: 'compatible' },
  { licenseA: 'apache-2.0', licenseB: 'cc0-1.0', compatibility: 'compatible' },
  { licenseA: 'apache-2.0', licenseB: 'mit', compatibility: 'compatible', conditions: 'Apache 2.0 has additional patent-related terms that may affect the combined work. Include NOTICE file.' },
  { licenseA: 'apache-2.0', licenseB: 'gpl-2.0', compatibility: 'incompatible', conditions: 'Apache 2.0 and GPLv2 are incompatible. GPLv2 does not include the patent grant required by Apache 2.0.' },
  { licenseA: 'apache-2.0', licenseB: 'gpl-3.0', compatibility: 'compatible', conditions: 'Apache 2.0 is compatible with GPLv3. GPLv3 includes a patent retaliation clause that satisfies Apache 2.0 requirements. Combined work must be under GPLv3.' },
  { licenseA: 'apache-2.0', licenseB: 'agpl-3.0', compatibility: 'compatible', conditions: 'Apache 2.0 is compatible with AGPLv3. Combined work must be under AGPLv3.' },
  { licenseA: 'apache-2.0', licenseB: 'lgpl-3.0', compatibility: 'compatible', conditions: 'Apache 2.0 code can be linked with LGPLv3 libraries. The LGPL component must remain under LGPL.' },
  { licenseA: 'apache-2.0', licenseB: 'mpl-2.0', compatibility: 'compatible', conditions: 'Apache 2.0 files can be included in MPL-2.0 projects with proper attribution.' },

  // GPL compatibilities
  { licenseA: 'gpl-3.0', licenseB: 'gpl-2.0', compatibility: 'incompatible', conditions: 'GPLv2 and GPLv3 are incompatible. GPLv2-only code cannot be combined with GPLv3 code. Use "GPLv2 or later" to bridge.' },
  { licenseA: 'gpl-3.0', licenseB: 'agpl-3.0', compatibility: 'incompatible', conditions: 'GPLv3 and AGPLv3 are not directly compatible. AGPL code cannot be incorporated into GPLv3 projects due to the additional network use requirement.' },
  { licenseA: 'gpl-3.0', licenseB: 'lgpl-3.0', compatibility: 'compatible', conditions: 'GPLv3 is compatible with LGPLv3. LGPLv3 code can be incorporated into GPLv3 projects (the result is under GPLv3).' },
  { licenseA: 'gpl-3.0', licenseB: 'mpl-2.0', compatibility: 'conditional', conditions: 'MPL-2.0 code can be included in GPLv3 projects under the GPL\'s terms, but the MPL-licensed files must remain available under MPL.' },
  { licenseA: 'gpl-2.0', licenseB: 'lgpl-2.1', compatibility: 'compatible', conditions: 'GPLv2 is compatible with LGPLv2.1. LGPLv2.1 code can be incorporated into GPLv2 projects.' },

  // AGPL compatibilities
  { licenseA: 'agpl-3.0', licenseB: 'lgpl-3.0', compatibility: 'compatible', conditions: 'AGPLv3 is compatible with LGPLv3. Combined work must be under AGPLv3.' },
  { licenseA: 'agpl-3.0', licenseB: 'mpl-2.0', compatibility: 'conditional', conditions: 'MPL-2.0 code can be included in AGPLv3 projects, but MPL files must remain available under MPL.' },

  // LGPL compatibilities
  { licenseA: 'lgpl-3.0', licenseB: 'lgpl-2.1', compatibility: 'incompatible', conditions: 'LGPLv3 and LGPLv2.1 are not compatible. Upgrade to LGPLv3 or use "LGPLv2.1 or later".' },
  { licenseA: 'lgpl-3.0', licenseB: 'mpl-2.0', compatibility: 'conditional', conditions: 'LGPLv3 and MPL-2.0 can be combined with careful consideration of the licensing terms for each file.' },
];

/**
 * Use case recommendations with detailed guidance.
 */
export const useCaseGuidance: Record<string, { description: string; topPicks: string[]; warnings: string[] }> = {
  personal: {
    description: 'Personal or hobby projects, not intended for commercial distribution.',
    topPicks: ['mit', 'isc', 'unlicense'],
    warnings: [
      'Even for personal projects, choosing a license matters if you ever share the code publicly.',
    ],
  },
  commercial: {
    description: 'Commercial software products distributed to customers.',
    topPicks: ['mit', 'apache-2.0', 'bsd-3-clause'],
    warnings: [
      'Avoid GPL-family licenses if you do not want to release your source code.',
      'LGPL is acceptable if you only link to the library without modifying it.',
      'Apache 2.0 provides patent protection for both contributors and users.',
    ],
  },
  saas: {
    description: 'Software provided as a hosted service (no distribution to customers).',
    topPicks: ['mit', 'apache-2.0', 'agpl-3.0'],
    warnings: [
      'GPL does not trigger on SaaS usage (no distribution occurs).',
      'Only AGPL triggers source disclosure for SaaS/network use.',
      'If your project uses AGPL libraries, you must offer source to your users.',
    ],
  },
  library: {
    description: 'Software libraries or frameworks intended to be used by other projects.',
    topPicks: ['mit', 'apache-2.0', 'lgpl-3.0', 'mpl-2.0'],
    warnings: [
      'Strong copyleft (GPL) libraries discourage adoption by proprietary projects.',
      'LGPL is designed specifically for libraries and allows proprietary linking.',
      'MIT/BSD libraries have the widest adoption potential.',
    ],
  },
  documentation: {
    description: 'Documentation, guides, tutorials, and written content.',
    topPicks: ['cc-by-4.0', 'cc-by-sa-4.0', 'cc0-1.0'],
    warnings: [
      'Use Creative Commons licenses for documentation, not software licenses.',
      'CC BY-SA is used by Wikipedia and is share-alike.',
      'CC0 dedicates work to the public domain with no restrictions.',
    ],
  },
  educational: {
    description: 'Educational materials, course content, and academic projects.',
    topPicks: ['mit', 'cc-by-4.0', 'gpl-3.0', 'cc0-1.0'],
    warnings: [
      'MIT is recommended for code examples that students should freely reuse.',
      'CC BY is standard for educational content and lecture materials.',
      'GPL ensures any improvements by students remain open.',
    ],
  },
};
